### ISSUE TITLE
Resize panels

### ISSUE THREAD

**Issue by Vanessa219** [b3log/wide#132]
* 文件树、输出窗口、编辑器的大小需要可以拖动， windows resize

**Comment by sebastianmacias** [comment]
Hi @88250, @Vanessa219,

Is there a timeline for this issue?

Thanks a lot for the great work so far.

**Comment by 88250** [comment]
Hi, @sebastianmacias 

We plan to finish it in version 1.5.0, before the end of the year.

Thank you! :grapes:

**Comment by 88250** [comment]
@sebastianmacias We have almost completed the development of this feature, please help us to test it.

**Comment by sebastianmacias** [comment]
Hi @88250, I have been out for a little while. As soon as I'm back I will test the latest changes and submit my feedback.

Thanks!
