### ISSUE TITLE
可配置文件树与 编辑器 Tab 同步

### ISSUE THREAD

**Issue by muyuballs** [b3log/wide#154]
文件Tab关闭后，左侧文件树会自动滚动到当前文件在文件树中的位置
建议增加一个开关，来控制Tab和文件树是否同步，如Eclipse：
![default](https://cloud.githubusercontent.com/assets/3403240/5066553/2b355daa-6e70-11e4-8ec7-5fe73fec1b50.png)

**Comment by 88250** [comment]
不配置了，默认同步吧。
