### ISSUE TITLE
文件树右键失效

### ISSUE THREAD

**Issue by ElvizLai** [b3log/wide#200]
邮件点击新建文件时，弹出的窗口一闪而过。无法点击。长按鼠标右键，弹出的窗口可持续显示，但是松开后消失，无法进行有效操作

系统：OS X 10.9.5

safari版本：7.1.2
chrome版本：39
firefox版本：36a2

**Comment by 88250** [comment]
暂时没有环境验证，稍微推后一点解决。

**Comment by gfoxiii** [comment]
ubuntu 14.10 & mac yosemite 都出现这个问题。
已经试过safari、chrome、firefox、chromium-browser都不行。右键之后，一闪即逝，无法进行选择。

**Comment by ElvizLai** [comment]
目前的解决方式是右键长按不放然后鼠标移过去后按下左键。。。

**Comment by 88250** [comment]
应该已经修复，请帮忙验证：https://wide.b3log.org

**Comment by ElvizLai** [comment]
嗯，这边safari测试已经可以正常使用。
系统版本10.10.2

**Comment by 88250** [comment]
I close this issue, thank you!

:grapes:
