### ISSUE TITLE
在docker里面运行怎么老是报错？

### ISSUE THREAD

**Issue by tonystz** [b3log/wide#201]
docker run  -p 10.64.71.20:7070 wide ./wide -docker=true -channel=ws://10.64.71.20:7070
错误：
```
outputs.go:119: fork/exec /wide/tonystz/src/hello/hello: invalid argument
```
运行完自带的hello，没有看到Println的输出结果

**Comment by 88250** [comment]
用这个启动试试：

`sudo docker run -p 127.0.0.1:7070:7070 88250/wide:latest ./wide -docker=true -channel=ws://127.0.0.1:7070`

**Comment by tonystz** [comment]
如果IP是127.0.0.1就没法从外面访问了

**Comment by tonystz** [comment]
那只能在本机访问了啊

**Comment by 88250** [comment]
把 127.0.0.1 换成外面可以访问的网卡 IP 就可以了 :-)

**Comment by tonystz** [comment]
我安装docker的机器IP是```10.64.71.20```
运行wide命令为```docker run -p 127.0.0.1:7070:7070 88250/wide:latest ./wide -docker=true -channel=ws://127.0.0.1:7070```
访问方式```http://10.64.71.20:7070```
如果是这样，根本没法访问到的

**Comment by 88250** [comment]
`docker run -p 10.64.71.20:7070:7070 88250/wide:latest ./wide -docker=true -channel=ws://10.64.71.20:7070`

**Comment by tonystz** [comment]
那和我问的问题是一样的啊；如果这样的话，执行里面的main.go是看不到```"Hello, 世界"```这样的输出的
^)^

**Comment by 88250** [comment]
我刚刚在本地测试过了，我这里 work 的。
你仔细看下命令，上面我打给你的和一开始你打的命令是不一样的 :ghost:

**Comment by 88250** [comment]
另外，docker 更新到最新版。

**Comment by tonystz** [comment]
我直接copy的你这个
```
docker run -p 10.64.71.20:7070:7070 88250/wide:latest ./wide -docker=true -channel=ws://10.64.71.20:7070
```
不行啊。这个是我的docker version
[root@CentOS7 ~]# docker version   
Client version: 1.3.2
Client API version: 1.15
Go version (client): go1.3.3
Git commit (client): 39fa2fa/1.3.2
OS/Arch (client): linux/amd64
Server version: 1.3.2
Server API version: 1.15
Go version (server): go1.3.3
Git commit (server): 39fa2fa/1.3.2

**Comment by 88250** [comment]
docker 版本看来没有问题。

wide 的镜像用最新的了么：`sudo docker pull 88250/wide:latest`

**Comment by tonystz** [comment]
是的 我只是用dock tag修改了一个名字
```
[root@CentOS7 ~]# docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
vtest               latest              e067f340f479        4 hours ago         534.6 MB
centos              latest              e3ca4021a707        4 hours ago         224 MB
88250/wide          latest              e51c919581d7        25 hours ago        544.4 MB
wide                latest              e51c919581d7        25 hours ago        544.4 MB
tonystz/mycentos    latest              f827f4a0bcbc        45 hours ago        413.2 MB
```

**Comment by 88250** [comment]
非 docker 方式你有试过么？

**Comment by 88250** [comment]
对了，这个是注册新用户后出现的么？

**Comment by tonystz** [comment]
是注册登录的

**Comment by 88250** [comment]
It's weird :weary: 

方便的话帮忙试试非 docker 方式，如果非 docker 方式 work，那就说明 docker 方式需要再进一步看看。

**Comment by 88250** [comment]
我关闭这个 issue 了，如果还有问题就 reopen
