### ISSUE TITLE
错误提示的UI有一个bug

### ISSUE THREAD

**Issue by fym201** [b3log/wide#208]
当在A标签保存文件时如果有错误会在错误的行显示一个”红X“标记错误位置，但是如果没修复这个错误的情况下切换到B标签，这个”红X“标记仍然会在B标签中显示,但实际上B标签里并没有错误

**Comment by 88250** [comment]
It's a bug, thank you for report it, we will fix it later.

**Comment by 88250** [comment]
我先关闭这个 issue 了 :green_apple:
