### ISSUE TITLE
产品定位 (Product Orientation)

### ISSUE THREAD

**Issue by 88250** [b3log/wide#209]
**该 issue 已经关闭，请到[黑客与画家的社区](http://symphony.b3log.org/article/1438407961481)参与讨论。**

---- 
目前我们认为：

**Wide 的目标不是彻底代替本地 IDE，而是做本地 IDE 很难做到的事情**

* 分享代码：类似 playground，但支持多文件并提供嵌入方式，在其他网站（比如技术社区帖子）展现、运行代码
* 团队协同：比如标记代码 issue 并通知、编辑状态显示，这个特性很类似一些即时战略游戏中的玩家协作，这里是特性设计：[英雄模式](https://docs.google.com/document/d/1s8OXa9skrTH053e4KZRHsJ14EblB6VFO7_2QyNrciF8/edit?usp=sharing)
* 随时随地：不用装环境（或者说不用经常升级吧 :ghost: ），能联网就能开发
* 支持移动设备，即使不支持开发（或者是支持的体验很差），但是可以运行，可以浏览代码
* 易于和其他系统进行集成、扩展
* ...

欢迎大家献计献策，让我们一起做出一个亮闪闪的开源项目！

**Comment by haorendashu** [comment]
>分享代码：类似 golang.org 的 playground，甚至可以提供嵌入方式，在其他网站（比如技术社区）运行代码

感觉对于这一点来说，wide显得太臃肿了

**Comment by 88250** [comment]
@haorendashu 多谢大叔建议，已经实现：https://wide.b3log.org/playground
