### ISSUE TITLE
Browser-less version of Wide

### ISSUE THREAD

**Issue by kokizzu** [b3log/wide#210]
Browser-less version of Wide, by embedding [WebKit](https://github.com/mattn/go-webkit) or using [XUL-Runner](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/XULRunner) on Wide's own client app.

That way, the Wide could use all keyboard shortcut (including [Ctrl+W](https://stackoverflow.com/questions/7295508) for closing editor tab), opening and editing files locally, that way Wide could replace common text editor such as [Brackets.io](http://brackets.io), [Atom.io](http://atom.io), [SublimeText](http://sublimetext.com) or [WebStorm](http://www.jetbrains.com/webstorm/).

**Comment by kokizzu** [comment]
Maybe could be done using Electron: https://github.com/atom/electron

**Comment by 88250** [comment]
We are working on the details of some features and bugs, this issue we will consider later.

Anyway, thanks your nice suggestion, have a :grapes:

**Comment by 88250** [comment]
I have tried use [thrust](https://github.com/breach/thrust), it works fine: 

![image](https://cloud.githubusercontent.com/assets/873584/9976634/cf5caeb8-5f1c-11e5-8bbb-b25984f8d651.png)

![image](https://cloud.githubusercontent.com/assets/873584/9976632/acd51588-5f1c-11e5-8b74-57fcea93091f.png)

Maybe I will start another project to do this, thank you again, it really a nice idea!

**Comment by kokizzu** [comment]
that's great :3

**Comment by 88250** [comment]
@kokizzu 

多谢你了，由衷肺腑。
