### ISSUE TITLE
需要更多运行时限制

### ISSUE THREAD

**Issue by doylecnn** [b3log/wide#211]
在wide 中编译并运行
```go
package main
import "fmt"
func main(){
    for{
        go func(){
            for{
                fmt.Println("Hello world!")
            }
        }()
    }
}
```
然后wide 网站本身就再也无响应了

在play.golang.org 上直接返回：
```
process took too long
Program exited.
```

实际上，wide 不需要真的可以执行所有的用户程序……内存限制和运行时间上的限制可以更紧一些……需要放开限制的话就付钱什么的……

**Comment by 88250** [comment]
已处理。

目前 B3log 官网提供的 [Wide 服务](https://wide.b3log.org )在运行的时候加入了内存限制，F 餐用户只允许使用 50M 内存，如果超过这个大小，用户程序会自动被 kill。


多谢反馈，一起吃串葡萄压压惊 :grapes:
