### ISSUE TITLE
lost password

### ISSUE THREAD

**Issue by micln** [b3log/wide#213]
how  to reset ?

**Comment by 88250** [comment]
Do you use our service (https://wide.b3log.org) or on your local?

**Comment by micln** [comment]
no...

I want to login here but it alway said "登录失败" https://wide.b3log.org/login

I'm sure I had signuped ...

**Comment by 88250** [comment]
Please give me your username, I reset password for you.

**Comment by micln** [comment]
kzzhr
thanks!

**Comment by 88250** [comment]
Your password have been reset to `123456`, login then change it :grapes:

**Comment by micln** [comment]
thx!
