### ISSUE TITLE
About forwarding the ws://{IP}:{PORT} service

### ISSUE THREAD

**Issue by wenris** [b3log/wide#214]
Nice job!

My problem is: I am running wide in a docker container, and the host can visit wide properly, but other hosts in the same local network cannot.

The reson is that wide tells its client to connect the ws channel at ws://172.17.0.3:80, where 172.17.0.3 is the container's IP.

This IP is inaccessible except by the host running the container.

Any quick sollution to this problem?

Thanks!

**Comment by 88250** [comment]
Hi, wenris

You can use the `-channel` parameter to solve the problem. 

https://github.com/b3log/wide#docker

**Comment by wenris** [comment]
Thanks, but this does not solve my problem. Here is my test enviorment:

Host A has IP addr as 10.10.1.2, and run docker with `./wide -p 80:80 `

**Comment by wenris** [comment]
OK, I solve this problem by `-channel ws://10.10.1.2`, it is not perfect but it works.
