### ISSUE TITLE
右键操作会受浏览器的鼠标动作影响

### ISSUE THREAD

**Issue by zlyang** [b3log/wide#216]
chrome+mouse gestrue，右键会受到影响

**Comment by 88250** [comment]
能稍微具体一点么？

**Comment by zlyang** [comment]
在mac上，用右键点出菜单后，就变成了鼠标手势，不能够点击

**Comment by thewhitetulip** [comment]
Can anyone translate to English?

**Comment by trinemax** [comment]
在mac上，用右键点出菜单后，就变成了鼠标手势，不能够点击
When using mac(Safari?),open menu with right click,cursor becomes to hand and can do nothing.

**Comment by 88250** [comment]
I will try to resolve this issue in several days, thank you guys.

**Comment by Vanessa219** [comment]
@zlyang 这个鼠标手势是个 Chrome 插件么？

**Comment by zlyang** [comment]
i do't have the environment now,sorry

**Comment by spance** [comment]
的确是，可能监听鼠标的方法可能要调整，右键鼠标事件被带有鼠标手势的插件捕获到了

**Comment by luxl** [comment]
我也是，安装了Chrome的手势插件，右键操作的时候事件被手势插件给捕获了，不会弹出相应的菜单。我用的Chrome插件是“miniGestures”。话说这个问题有点久了呢

**Comment by 88250** [comment]
暂时不考虑解决了，感谢各位支持。
