### ISSUE TITLE
同包下自动完成不提示 same package autocomplete not working

### ISSUE THREAD

**Issue by DreamUFO** [b3log/wide#217]
无意间发现的(小BUG,暂时定性为BUG吧). 没有验证其他命名的包
同在main包下 我定义了一个结构 Test 并加了个测试方法
发现在main函数里面 Test. 自动完成获取的是空。。。 
如果有时间的话就解决下吧 
不是什么大问题 不影响WIDE整体的 使用
浏览器:chrome 版本 36.0.1985.125 
OS:WIN7 OEM SP1
![image](https://cloud.githubusercontent.com/assets/10512112/6568110/29505b2a-c70d-11e4-83a8-2bd055739946.png)

![image](https://cloud.githubusercontent.com/assets/10512112/6568101/1749f6f2-c70d-11e4-97ec-f98199d6bc1d.png)

**Comment by 88250** [comment]
的确有这个 bug。只要是同包（不只是 main 包）不同文件的时候都能重现。
可能是调用 `gocode` 的时候用法不大对，我研究一下，多谢反馈 :grapes:

**Comment by DreamUFO** [comment]
谢谢你的回复 我已经收到你的邮件 感谢你们提供这么好的一个平台

**Comment by 88250** [comment]
已经修复并部署，有空请帮忙验证 :smile:

**Comment by DreamUFO** [comment]
收到你的邮件了  已验证 提到的问题已修复  谢谢！你们效率真高
