### ISSUE TITLE
自由注册账号的问题

### ISSUE THREAD

**Issue by erasin** [b3log/wide#219]
我不清楚是否另有设计。

如果一个陌生人知道部署在wide上的地址就可以随时注册个新的账号，这也太危险了吧。
可不可以默认的管理员来添加账号，而不是自由的创建。
或者用处创建后，默认管理人审核通过后处理。

**Comment by 88250** [comment]
多谢反馈 :grapes: 

加了个配置项 `AllowRegister` 在 wide.json 里，标识是否开启帐号注册。

请重新[下载](http://pan.baidu.com/s/1dD3XwOT)或 pull。
