### ISSUE TITLE
HTML 编辑器增强

### ISSUE THREAD

**Issue by gfoxiii** [b3log/wide#220]
建议添加在html编辑器上加上emmet

**Comment by 88250** [comment]
好的，计划在 1.3.0 里面加入该功能。

多谢反馈 :grapes:

**Comment by 88250** [comment]
这里是快捷键列表：https://github.com/emmetio/codemirror#default-keybindings

有几个快捷键和现有快捷键有冲突了，不过应该不影响主体使用（如果影响，请反馈）

----

1.2.0 [下载包](http://pan.baidu.com/s/1dD3XwOT)已经更新，也可以到 https://wide.b3log.org 体验 :smile:
