### ISSUE TITLE
Import zip file

### ISSUE THREAD

**Issue by mindfocus** [b3log/wide#222]
提供压缩包导入功能，从其他的项目导入到 wide 中时提供解压缩 zip 包的功能
更方便导入

**Comment by 88250** [comment]
It's a good suggestion, I will implement it in recent days, thanks.

**Comment by 88250** [comment]
![import](https://cloud.githubusercontent.com/assets/873584/6767938/42233628-d08a-11e4-9b1a-cc1864fa27a2.png)
![upload](https://cloud.githubusercontent.com/assets/873584/6767939/42246548-d08a-11e4-90f9-e5fe1760c229.png)
![upload2](https://cloud.githubusercontent.com/assets/873584/6767940/422df7d4-d08a-11e4-9993-e1a138c8f5c7.png)
![decompress](https://cloud.githubusercontent.com/assets/873584/6767941/422e9ffe-d08a-11e4-9047-2ab01fc20fd4.png)
