### ISSUE TITLE
1.2找不到shell

### ISSUE THREAD

**Issue by lokisw** [b3log/wide#225]
1.2找不到shell 文档里不 是有说有shell 功能吗

**Comment by 88250** [comment]
shell 功能目前还没有开发完，暂时不可用 :shell:

**Comment by lokisw** [comment]
谢谢。能不能在wide加入vim模式 。有些快捷链用习惯 了。codemirror里已经有这个了。

**Comment by 88250** [comment]
嗯，请 watch issue：https://github.com/b3log/wide/issues/83

这个 issue 我关闭了，谢谢你的反馈 :grapes:
