### ISSUE TITLE
文件夹重命名时有bug

### ISSUE THREAD

**Issue by lokisw** [b3log/wide#226]
文件夹重命名时有bug,会把文件夹变成文件。然后能不能增加文件和方件夹复制移动功能，还有 由于有时候会用到cgo,希望也可以增加c语言的显示

**Comment by 88250** [comment]
重命名的 bug 已经修复。复制文件的特性请 watch 这个 issue：https://github.com/b3log/wide/issues/190
另外，C 语言的显示可以添加高亮，请再提交一个 issue 

多谢反馈！ :grapes:
