### ISSUE TITLE
Cross Compilation

### ISSUE THREAD

**Issue by HydeZhaoToo** [b3log/wide#231]
wide很好用 我跟同事晚上一起玩代码在用， 最近玩树莓派，想着如果有交叉编译功能就完美了 这样不用每次cp代码到本地编译了。

**Comment by 88250** [comment]
这两天我想了一下，交叉编译可以这样做：

1. 提供单独的“构建并下载”选项
2. 在选项中选择 Wide 提供的编译环境（Wide 启动的时候回判断，如果支持目标环境的编译就提供这个选项）
3. 构建后弹框提示下载二进制（不提供打包，比如其他资源）
4. 下载完后 Wide 自动删除该二进制

兄台你看这个流程如何？

**Comment by 88250** [comment]
目前界面是这样的，后面菜单会调整成二级菜单：

**Comment by 88250** [comment]
![image](https://cloud.githubusercontent.com/assets/873584/9287365/af3062a0-4343-11e5-9706-228117252139.png)

后面考虑使用二级菜单。
