### ISSUE TITLE
Users keep getting created in /

### ISSUE THREAD

**Issue by Xe** [b3log/wide#233]
I am using the following Dockerfile:

```Dockerfile
FROM golang:1.4.2

RUN groupadd -g 3434 wide
RUN adduser wide \
		--uid 3434 \
		--gid 3434 \
		--home /wide/data

USER wide
ADD ./wide-1.3.0-linux-amd64.tar.gz /wide/app
ADD ./style.css /wide/app/static/user/admin/style.css

USER root
ADD ./start.sh /
ADD ./run.sh /

EXPOSE 7070
CMD /start.sh
```

With the following scripts:

```shell
#!/bin/bash
# start.sh

chown -R 3434:3434 /wide/app /wide/data
chmod -R a+rwx /wide/data

su wide '/run.sh'
```

```shell
#!/bin/bash
# run.sh

export PATH=/go/bin:/usr/src/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

cd /wide/app
./wide
```

But whenever I try to create an account, it shows up with its path as `//<username>` instead of `/wide/data/<username>`.

![](https://i.imgur.com/J85JMIG.png)

How can I make the users be created in `/wide/data/<username>`?

**Comment by 88250** [comment]
Hi,

You should change the `first user` (admin)'s `Workspace` in the `conf/users/admin.json'.

**Comment by Xe** [comment]
That seemed to do it. Thanks!
