### ISSUE TITLE
go: cannot find GOROOT directory: /home/daniel/go

### ISSUE THREAD

**Issue by gedw99** [b3log/wide#234]
installed on my OSX

my username is not Daniel. Looks like a hard coded in the code ?

**Comment by gedw99** [comment]
gedw99-MacBook-Pro:wide-1.3.0-darwin-amd64 apple$ go env
GOARCH="amd64"
GOBIN="/Users/apple/Workspace/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/apple/Workspace"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT=""
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
gedw99-MacBook-Pro:wide-1.3.0-darwin-amd64 apple$

**Comment by 88250** [comment]
The default user is `admin`/`admin`
