### ISSUE TITLE
重复build&Run 第二次以后就只build 不Run了

### ISSUE THREAD

**Issue by ZeaLoVe** [b3log/wide#237]
主要在执行 open-falcon 的query组件的时候遇到的，其他项目不知道会不会这样。
第二次后就没办法Run程序了，只能build

**Comment by 88250** [comment]
这个项目我不太清楚，暂时不去查了，请理解。

如果你找到了问题或者能在其他普通一点的项目中重现，请重新打开这个 issue。

周末愉快 :grapes:
