### ISSUE TITLE
mac miss wide.json

### ISSUE THREAD

**Issue by yuchangfu** [b3log/wide#238]
E 2015/08/23 01:07:03 wide.go:146: open conf/wide.json: no such file or directory

I checked there has wide.json

**Comment by 88250** [comment]
Please give me the full path of the working directory of you Wide.

**Comment by yuchangfu** [comment]
/Application/wide

**Comment by 88250** [comment]
It's weird. I will track it in a few days.

**Comment by 88250** [comment]
Executes Wide directly this issue will occur, but if we run Wide in a terminal, all going well.
