### ISSUE TITLE
Run wide on localhost

### ISSUE THREAD

**Issue by thewhitetulip** [b3log/wide#240]
I tried running wide on localhost, it didn't work, it says cannot find local IP address, wide should provide a way to run on the localhost too.

**Comment by 88250** [comment]
Now, we can use `--ip=localhost` to specified it.

**Comment by thewhitetulip** [comment]
Hey, last night I was trying to fix this, I wasn't able to do :D 
I tried assigning the local host IP on lung #200 and commented out the Exit function, or didn't work, can you please tell me why?

**Comment by 88250** [comment]
See the [changes], I think it is a better way. (https://github.com/b3log/wide/commit/5259b5430406f58e27842d63b9ddeb05eafeb18c)
