### ISSUE TITLE
Socket isn't released after program is quit

### ISSUE THREAD

**Issue by thewhitetulip** [b3log/wide#242]
I was working on a webapp and the port wasn't released by wide when I stopped the execution

**Comment by 88250** [comment]
Can you reproduce it still?

**Comment by thewhitetulip** [comment]
At least on my linux box, yes. When I run the same program from the commandline the socket is released when I stop the execution i.e. doing Ctrl + C, but when running it on wide the socket is not released because the process is still running in the background

**Comment by 88250** [comment]
Can you send me (dl88250@gmail.com) your project code?

**Comment by 88250** [comment]
I run your project on Win10, it works fine.

Wide stop execution process by kill API: https://github.com/b3log/wide/blob/master/output/processes.go#L88
