### ISSUE TITLE
編輯時換行的問題

### ISSUE THREAD

**Issue by shiyou0130011** [b3log/wide#243]
當我在 playground 頁編輯程式時，按下 Enter 鍵換行時的縮排是空格而不是 tab

例如，當code如下：

    fmt.Println("Hello, 世界") // 開頭為 tab

然後我在最後換行，會是

    fmt.Println("Hello, 世界")
    // 新的一行，開頭為 4 個空格

若要變成像下面這樣，還要按一下<kdb> Format </kdb>：

    fmt.Println("Hello, 世界")
    // 新的一行，開頭為 tab

**Comment by 88250** [comment]
明白了，稍后调整，多谢反馈~
