### ISSUE TITLE
If I forget the password,what should I do?

### ISSUE THREAD

**Issue by rivencxl** [b3log/wide#245]
There is no way to change my password when I forgot the password.

**Comment by 88250** [comment]
Our provided [Wide](https://wide.b3log.org) or your local Wide?

**Comment by rivencxl** [comment]
The online wide.

**Comment by 88250** [comment]
Give me your username, I will reset it :)

**Comment by 88250** [comment]
username and email

**Comment by rivencxl** [comment]
username:smartCXL
email:545167289@qq.com
Thku!

**Comment by 88250** [comment]
Do you try login with `SmartCXL`?

**Comment by 88250** [comment]
The username is case sensitive.

**Comment by rivencxl** [comment]
Thank you!!!

**Comment by 88250** [comment]
Login sucessfully?

**Comment by rivencxl** [comment]
I've forgotten my username....lol

**Comment by rivencxl** [comment]
yeah!

**Comment by 88250** [comment]
哈哈，你是中国人吧....

**Comment by rivencxl** [comment]
shide!  haha  
 My input method has something worry and I can't remove it or install a new input method !

**Comment by 88250** [comment]
真是够悲催.... 来，注册一发黑客派吧：http://hacpai.com/register?r=88250

**Comment by 88250** [comment]
对了，这个 issue 我关闭了哟。

**Comment by rivencxl** [comment]
OK!
