### ISSUE TITLE
sessions.go:509: open /Users/Jase/golang/jase/src/web: too many open files/Users/Jase/golang/jase/src/web

### ISSUE THREAD

**Issue by jasey** [b3log/wide#246]
Great project with really great potential, however I get the following issue when I try to re-run wide and open my project in the browser 

sessions.go:509: open /Users/Jase/golang/jase/src/web: too many open files/Users/Jase/golang/jase/src/web

I get this error for every folder in the project and I am unable to open it in the browser.

Im on darwin_amd64 - https://gist.github.com/jasey/1a035421a9b1591fd462

**Comment by 88250** [comment]
Try the followings:

1. Increase the open files limit by editing `~/.bash_profile`, inserts `ulimit -n 10240`, then save and exit.
2. Open another terminal shell and startup Wide
