### ISSUE TITLE
新建文件后，双击打不开

### ISSUE THREAD

**Issue by gitwillsky** [b3log/wide#247]
如题，必须刷新浏览器后才能正常打开。

**Comment by 88250** [comment]
本地环境还是？

**Comment by gitwillsky** [comment]
服务器，在官方体验服务器上也是这样。双击新建的go文件无法在editor中render.

**Comment by 88250** [comment]
发现问题了，多谢反馈，稍后修复！

**Comment by 88250** [comment]
Wide 在线环境应该已经修复，请帮忙验证。

**Comment by gitwillsky** [comment]
已经修复。

**Comment by 88250** [comment]
我已经重新上传发布包了，如需要请重新[下载](http://pan.baidu.com/s/1dD3XwOT) :grapes:
