### ISSUE TITLE
git clone bitbucket项目失败

### ISSUE THREAD

**Issue by ardypro** [b3log/wide#254]
clone时，file中File清单中没有从服务器克隆任何文件，点击几次clone，整个File列表框里变成空白，需要refresh整个页面才正常。是不是只能clone github里的项目？

**Comment by 88250** [comment]
实现上面是调用了 `git clone` 命令，应该可以 clone 任何 git 项目的。

在线环境上面由于带宽限制以及墙内网络原因，可能存在问题。
