### ISSUE TITLE
新用户的Workspace问题

### ISSUE THREAD

**Issue by nzlov** [b3log/wide#259]
如何设置新建用户的Workspace？只能默认$HOME？

**Comment by 88250** [comment]
Workspace 是根据 admin 用户而来的，可以修改一下 conf/users/admin.json 里面的配置，重启就好了。

**Comment by nzlov** [comment]
admin.json 设置为%GOPATH 但是新建的用户还是$HOME下

**Comment by 88250** [comment]
取的是 admin 用户 Workspace 的父目录。

**Comment by 88250** [comment]
我关闭这个 issue 了，如果还有问题，你再 reopen it。
