### ISSUE TITLE
用户起始页 社区栏 下边的连接有误 导致 不能打开

### ISSUE THREAD

**Issue by DreamUFO** [b3log/wide#263]
登录后  在用户的首页  起始页面板下
左边 是 WIDE  右边是 社区
社区下边的 连接是错误的 比如 
Golang 实现添加文件头的小工具  2016-01-05  的连接是 
http://hacpai.comhttp//hacpai.com/article/1451959349092
而正确的 应该是 http://hacpai.com/article/1451959349092
希望 有空的话 修复这个小小的问题吧

我的WIDE用户名是  zyhj

**Comment by 88250** [comment]
http://wide.b3log.org 已结更新，多谢反馈了！
