### ISSUE TITLE
Safe config file save

### ISSUE THREAD

**Issue by kardianos** [b3log/wide#264]
When using on a small device, sometimes the power suddenly turns off. When this happens it is not uncommon for a config file to be truncated without the content flushed to disk, so I just get an empty config file.

I would recommend you use https://github.com/dchest/safefile for saving config files to disk.

**Comment by 88250** [comment]
I will try to fix it, thank you :grapes:

**Comment by 88250** [comment]
I can't reproduce this issue, so I added some logging codes to locate it.

Could you build Wide with the latest source codes and help me debug it, thanks.
