### ISSUE TITLE
Backup files in config create errors

### ISSUE THREAD

**Issue by plinyGo** [b3log/wide#267]
Some GUIs in Linux create backup files when a file is deleted, usually by adding ~ to the filename. These files are then not shown in the explorer (but can be displayed in the terminal).
If there are 2 user config files in the config folder (e.g. conf/users/user1.json and conf/users/user1.json~), both are apparently parsed by wide on startup, which results in a fatal error on startup, caused by duplicate http bindings. 

I think several issues are at play here:
1. Files that end with ~ should not be parsed
2. If duplicate config files are in the system (e.g. 2 files with same username), this should be catched as an error and not result in an unhandled errors in other libraries

Please let me know if you need more info to reproduce the issue.

Thanks!

**Comment by 88250** [comment]
Thank you, I will fix it.
