### ISSUE TITLE
Absolute paths prevent reverse proxies

### ISSUE THREAD

**Issue by plinyGo** [b3log/wide#268]
I tried to use wide behind an apache2 reverse proxy configuration to make it reachable from the outside and have better control over access to the system.
Absolute paths make this more cumbersome, but can usually be resolved by using mod_proxy and mod_proxy_html. 
However, in at least one case (/views/login.html:67), there is an absolute path within javascript, which cannot be resolved by mod_proxy_html.

I think it would be safer to replace absolute paths with relative paths where possible, as this shouldn't affect the system when used without a proxy, and make it much easier to use it behind apache2 (and probably nginx).

**Comment by 88250** [comment]
Thank you, I will trace it later soon :smirk:

**Comment by 88250** [comment]
It may be a problem. I think use a reverse proxy for Wide you have to handle a few kinks, such as WebSocket connecting.

So, uses a sub domain like 'wide.yourdomainame.com' is more preferable.

**Comment by 88250** [comment]
```json
{
    "IP": "${ip}",
    "Port": "7070",
    "Context": "/wide",  // change here
    "Server": "{IP}:{Port}",
    "StaticServer": "/wide", // change here
    "LogLevel": "debug",
    "Channel": "ws://{IP}:{Port}/wide", // change here
    "HTTPSessionMaxAge": 86400,
    "StaticResourceVersion": "${time}",
    "MaxProcs": 4,
    "RuntimeMode": "dev",
    "WD": "${pwd}",
    "Locale": "en_US",
    "Playground": "${home}/playground",
    "AllowRegister": true,
    "Autocomplete": true
}
```

Please help me to verify it, thank you :grapes:

**Comment by plinyGo** [comment]
Looks good now, thanks for the quick fix!
