### ISSUE TITLE
提两建议

### ISSUE THREAD

**Issue by tzraeq** [b3log/wide#273]
你好，我想提两点改进建议
1.workspace下面最好可以再多一级，以project为单位，因为很多时候都是使用make去编译的
2.在Makefile上右键，可以对Makefile中的tag进行遍历，并可以执行指定的tag

以上两点是我认为比较贴近实际的需求，希望采纳。另外，请问调试功能您计划什么时候完成呢？

**Comment by 88250** [comment]
* 现在的编译规则都是标准的 go 规则，请允许我们继续维持这个规则下去

Debug 的支持说实话我心里没底。前期已经选择了一些 debug tool 跟进，但是效果都不理想，如果自己写，又不太现实，这一点也请理解。

**Comment by 88250** [comment]
#8

**Comment by 88250** [comment]
这个 issue 我关闭了，关于 debugger 请关注 #8 ，感谢你的反馈。
