### ISSUE TITLE
IDE Freeze

### ISSUE THREAD

**Issue by ppey** [b3log/wide#277]
I tried to run the game of life example from [glang.org](https://golang.org/doc/play/life.go) using latest wide and go 1.6.2 on  linux/amd64.

This code causes the tab in my chrome browser to freeze until the application is done. Beside this, clearing the terminal output using fmt.Print("\x0c") does not work, which might be an intended behavior.

**Comment by 88250** [comment]
Thank you for report this issue, I will follow it up.
