### ISSUE TITLE
[Ctrl]+[Shift]+F associated twice

### ISSUE THREAD

**Issue by dx034** [b3log/wide#281]
According to the toolbar, the combination [Ctrl]+[Shift]+F is associated with both Source->Format, as well as with Find->Replace. It always reacts to Find->Replace in my installation. 
Source->Format should thus have another hotkey to make it usable.

Going through the source code (static/js/hotkeys.js) I actually think that [Ctrl]+[Shift]+F is not implemented at all at the moment. The behavior falls back to [Ctrl]+F in this case.

**Comment by 88250** [comment]
Source format: Alt-Shift-F
