### ISSUE TITLE
按ctrl+left, down..时文件树与 output window 隐藏

### ISSUE THREAD

**Issue by khjde1207** [b3log/wide#283]
wide/static/js/lib/jquery-layout/jquery.layout-latest.js  - 3375横 
            if (s.isHidden)
                show(pane); // will call 'open' after unhiding it
            else if (s.isClosed)
                open(pane, !!slide);
            else
                close(pane);
原因就是6横。 
把它删掉就可以了。
谁知道把ctrl+、的自动提示替换为 ctrl+space 的方法？

**Comment by 88250** [comment]
Ctrl-方向键是个快捷键特性，不是 bug 哦。可以把一些面板收起/展开。另外，快捷键目前没有自定义功能，欢迎关注 #18 。

**Comment by khjde1207** [comment]
谢谢！
