### ISSUE TITLE
Support cross-compiliation for windows_386

### ISSUE THREAD

**Issue by khjde1207** [b3log/wide#284]
鼠标右键弹出的窗口有windows_arm64， 但没有windows_386. 
怎么弄也不弹出windows_386选项，求助！！！ 
![2](https://cloud.githubusercontent.com/assets/18232924/19582353/b6e67cde-976e-11e6-82b2-43452104a800.png)

**Comment by 88250** [comment]
看截图好像你使用的是本地版？

如果要支持交叉编译，需要自己把其他环境编译好哦。

PS 那个是韩语么？欢迎 Pull Request 贡献一下哦~

**Comment by khjde1207** [comment]
环境已经设置完了. 
看图， 可以编译 386 Windows
我用的是arm树莓派。
![test](https://cloud.githubusercontent.com/assets/18232924/19671480/fa91e336-9aa9-11e6-9c3a-c81cabbbd623.png)

PS 是韩语，我翻译的，我头一次用git，上传了好几次，没变化。
我再试试。 谢谢

**Comment by 88250** [comment]
获取交叉编译环境的代码在 https://github.com/b3log/wide/blob/master/util/go.go#L36
麻烦你运行一下单元测试看看输出结果 https://github.com/b3log/wide/blob/master/util/go_test.go#L24

PS 韩语那个 PR 因为分支不对被我关闭了，麻烦你重新从自己的分支 PR 过来 : )

**Comment by khjde1207** [comment]
谢谢我试试， 
韩语json 我再次Pull Request 了。 这样行吗？ 
觉得git很难。
 谢谢

**Comment by 88250** [comment]
好的，麻烦帮忙看下，有可能是代码 bug，顺便看下你的 go 版本。
PR 已经合并了，非常感谢！

**Comment by khjde1207** [comment]
结果是这样的。

package main

import (
	"fmt"
	"os"
	"runtime"
)

func main() {

	toolDir := runtime.GOROOT() + "/pkg/tool"
	f, _ := os.Open(toolDir)
	names, _ := f.Readdirnames(-1)
	f.Close()
	fmt.Println(names)
	for _, name := range names {
		subDir, _ := os.Open(toolDir + "/" + name)
		tools, _ := subDir.Readdirnames(10)
		subDir.Close()

		if len(tools) > 5 {
			fmt.Println(name)
		}
	}

}


![111](https://cloud.githubusercontent.com/assets/18232924/19675633/59554ae6-9aca-11e6-83b2-4f2c8631da47.png)

**Comment by khjde1207** [comment]
找到了。 
view 458横 
 {{if eq . "darwin_amd64" "linux_amd64" "windows_amd64" "linux_arm"}}
修改
 {{if eq . "darwin_amd64" "linux_amd64" "windows_amd64" "linux_arm" "windows_386" "linux_386"}}
![333](https://cloud.githubusercontent.com/assets/18232924/19675839/ac975c98-9acb-11e6-8f70-b29f909c982b.png)

**Comment by 88250** [comment]
咦，看上去读出来了。这样，你在 index 页面上浏览器看下 HTML，搜索 crossCompile 看看。

**Comment by khjde1207** [comment]
好的今天我学了很多呢。非常感谢！

**Comment by 88250** [comment]
客气，欢迎来社区讨论： https://hacpai.com
