### ISSUE TITLE
ubuntu16.04运行，没有界面，只有这样的提示

### ISSUE THREAD

**Issue by besthyhy2** [b3log/wide#291]
besthyhy@X:~/bin/goes/wide-1.5.1-linux-amd64$ ./wide 
D 2016/11/23 12:21:02 wide.go:171: Conf: 
{
    "IP": "${ip}",
    "Port": "7070",
    "Context": "",
    "Server": "{IP}:{Port}",
    "StaticServer": "",
    "LogLevel": "debug",
    "Channel": "ws://{IP}:{Port}",
    "HTTPSessionMaxAge": 86400,
    "StaticResourceVersion": "${time}",
    "MaxProcs": 4,
    "RuntimeMode": "dev",
    "WD": "${pwd}",
    "Locale": "en_US",
    "Playground": "${home}/playground",
    "AllowRegister": true,
    "Autocomplete": true
}
D 2016/11/23 12:21:02 wide.go:175: ${pwd} [/home/besthyhy/bin/goes/wide-1.5.1-linux-amd64]
D 2016/11/23 12:21:02 wide.go:185: ${user.home} [/home/besthyhy]
D 2016/11/23 12:21:02 wide.go:212: ${ip} [192.168.0.114]
D 2016/11/23 12:21:02 wide.go:243: ${time} [1479874862975205092]
D 2016/11/23 12:21:03 main.go:90: host [go1.5.1, linux_amd64], cross-compilation [linux_amd64]
I 2016/11/23 12:21:03 main.go:187: Wide is running [192.168.0.114:7070]

**Comment by 88250** [comment]
最后这句日志：

```
I 2016/11/23 12:21:03 main.go:187: Wide is running [192.168.0.114:7070]
```

说明已经启动好了，你用浏览器访问这个地址就行了。
