### ISSUE TITLE
Feature idea: dart integration

### ISSUE THREAD

**Issue by gedw99** [b3log/wide#292]
I have been using Dart to build my client GUI for a while, with golang on all servers.

Dart allows me to build web clients and mobile native clients using flutter that run on android and iOS with no code differences.

There is a dart wed ide call dart pad that is itself all written in dart. It's really good too and have type ahead, type checking, Go To Definition , and very soon real time debugging. On the Server zou Just need To Run a Simple Dart code analyser and it Just Works.

So because Wide exists and jas lots of the extra things needed i feel that plugging in dart Pad makes allot of sense.

Also To extend this Fürther i am using gitlab at the Moment. Its able To be booted as a docker on YouTube Cloud but has CI Pipelines fully i tegrated and will Spawn All the docker Images you need for Testung Big Projects.

Lastly i want To i tegrated Cloud based Desktops and mobiles into the CI Pipelines. This Covers you Unit Tests running there too.
Saucelabs is ok for Mobile, and Desktops Can also be spun up via third parties. Habe Not looked too hard yet.

All of this gets zou running everything your Team needs in the Cloud.
My reasons for this as because i work with heavily distributed Teams with a huge number of microservices. It gets Out of Controller with each Developer running everything on their lo al Laptops.

Golang and Dart are excellent techlogy Matches too.

Its anyones Else into this idea ?

**Comment by 88250** [comment]
It sounds very cool! I am not familiar with Dart, maybe you can contribute it :)

**Comment by gedw99** [comment]
I can.

But I need more info on how wide works.
There are not really any docs.

Not sure if your aware but recently an open standard for IDE's and the way languages are integrated has been agreed. Most of the big names are in it. Ms, Google etc.

It would make allot is sense to adopt it.

The Che project of eclipse hase

**Comment by gedw99** [comment]
http://www.eclipse.org/che/
