### ISSUE TITLE
To change the signup user's location

### ISSUE THREAD

**Issue by chinglinwen** [b3log/wide#293]
Put the signup user's directory store in home, will cause chaos, It should be self contain( or support to change the location).

Expect /home/wen/wide
got /home/wen

config file:
```
{
    "IP": "${ip}",
    "Port": "3003",
    "Context": "",
    "Server": "{IP}:{Port}",
    "StaticServer": "",
    "LogLevel": "debug",
    "Channel": "ws://{IP}:{Port}",
    "HTTPSessionMaxAge": 86400,
    "StaticResourceVersion": "${time}",
    "MaxProcs": 4,
    "RuntimeMode": "dev",
    "WD": "${pwd}",
    "Locale": "en_US",
    "Playground": "${home}/wide/playground",
    "AllowRegister": true,
    "Autocomplete": true
}
```
D 2016/12/14 16:19:29 wide.go:175: ${pwd} [/home/wen/wide]
D 2016/12/14 16:19:29 wide.go:185: ${user.home} [/home/wen]

version:
wide-1.5.1-linux-amd64 ( expect command have -version too )

**Comment by 88250** [comment]
Hi, please check `Workspace` in `conf/users/admin.json`, the following signup users will use this path.

**Comment by chinglinwen** [comment]
Thank you, it's done,  and I found it's use the parent directory

So in order to put all users into /home/wen/wide/users, I have to write it this way

`"Workspace": "/home/wen/wide/users/workspace"`

**Comment by chinglinwen** [comment]
And I propose to put admin.json at the same level as wide.json

**Comment by chinglinwen** [comment]
Or another (my humble) idea, to make workspace more intuitively say "usershome" for wide.json

**Comment by 88250** [comment]
"admin" also a user in current design, so just change admin's conf file.

**Comment by chinglinwen** [comment]
That's feels okay for admin user

**Comment by 88250** [comment]
> Or another (my humble) idea, to make workspace more intuitively say "usershome" for wide.json

It's a good idea, I will accomplish it recently, thank you :)

**Comment by chinglinwen** [comment]
Great.

**Comment by 88250** [comment]
@chinglinwen I have committed code, please help me to test it :)

https://github.com/b3log/wide/blob/master/conf/wide.json#L16

**Comment by chinglinwen** [comment]
Sorry for the late
I tested it, the workspace is what I expect the way it works, but I think the following may need to consider

"WD": "${pwd}",
"UsersWorkspaces": "${WD}/workspaces",

This default config may indicate the workspace is in pwd, but it's not, it's in GOPATH

While I build it, I also found the deploy code and source code mixed up,  I think there maybe a better way to organize your code

Say using specific `src` for all srouce code ( only a suggestion, myself may not knowing that well )

Your release compress file is clean though

**Comment by chinglinwen** [comment]
Sorry for the late
I tested it, the workspace is what I expect the way it works, but I think the following may need to consider

"WD": "${pwd}",
"UsersWorkspaces": "${WD}/workspaces",

This default config may indicate the workspace is in pwd, but it's not, it's in GOPATH

While I build it, I also found the deploy code and source code mixed up,  I think there maybe a better way to organize your code

Say using specific `src` for all srouce code ( only a suggestion, myself may not knowing that well )

Your release compress file is clean though

**Comment by 88250** [comment]
Thank you :)
