### ISSUE TITLE
Clone a git repo issue

### ISSUE THREAD

**Issue by chinglinwen** [b3log/wide#294]
example clone url: http://192.168.100.93:3000/wenzhenglin/smail

Clone does the job, but introduce many git files (mess the directory structure )

![import_issue](https://cloud.githubusercontent.com/assets/16344129/21175313/968762e0-c21c-11e6-9b7d-4446c3708ca6.png)

version: wide-1.5.1-linux-amd64

**Comment by chinglinwen** [comment]
By restart wide, it then display correctly.

**Comment by 88250** [comment]
We will remove git support in https://github.com/b3log/wide/issues/356
