### ISSUE TITLE
with myself dockfile , fork/exec playground  permission denied

### ISSUE THREAD

**Issue by xladykiller** [b3log/wide#295]
**1. this is my dockfile:**

FROM centos:6.6

MAINTAINER pangm "shizc@asto-inc.com" 2016.12.15

ENV DEBIAN_FRONTEND noninteractive
ENV GOROOT /root/go/
ENV GOPATH /root/gopath/
ENV PATH $PATH:$GOROOT/bin/:$GOPATH/bin/
ENV TMPDIR /root/playground/

RUN useradd wide && useradd runner

RUN mkdir /root/gopath

ADD bin /root/bin

ADD conf /root/conf/

ADD static /root/static/

COPY views /root/views/

ADD go /root/go/

COPY gocode /root/gocode

COPY gotools /root/gotools

#COPY gotools /root/gopath/src/github.com/visualfc/gotools/

#COPY gocode /root/gopath/src/github.com/nsf/gocode/

RUN chmod +x /root/bin
RUN chmod +x /root/gocode
RUN chmod +x /root/gotools
RUN chmod -R +x /root/go/bin/

EXPOSE 17070

WORKDIR /root

CMD ["/root/bin","-docker=true","-channel=ws://192.168.7.7:17070"]

**2. this is my startup script:**

#!/usr/bin/env bash

sudo docker build -t wide .

sudo docker kill wide

sudo docker rm wide

#sudo docker run -it -d -p 7070:17070 -v /data/logs/ddd/:/data/logs/ddd --name wide wide:latest
sudo docker run -it -d -p 17070:17070 --name wide wide:latest

**3. the result: when i run the playground, it show me permission denied**

{
    "IP": "${ip}",
    "Port": "17070",
    "Context": "",
    "Server": "{IP}:{Port}",
    "StaticServer": "",
    "LogLevel": "debug",
    "Channel": "ws://192.168.7.7:{Port}",
    "HTTPSessionMaxAge": 86400,
    "StaticResourceVersion": "${time}",
    "MaxProcs": 4,
    "RuntimeMode": "dev",
    "WD": "${pwd}",
    "Locale": "en_US",
    "Playground": "${home}/playground",
    "UsersWorkspaces": "${WD}/workspaces",
    "AllowRegister": true,
    "Autocomplete": true
}
D 2016/12/15 08:17:32 wide.go:176: ${pwd} [/root]
D 2016/12/15 08:17:32 wide.go:186: ${user.home} [/root]
D 2016/12/15 08:17:32 wide.go:221: ${ip} [172.17.0.71]
D 2016/12/15 08:17:32 wide.go:252: ${time} [1481789852658086506]
D 2016/12/15 08:17:32 main.go:91: host [go1.7.4, linux_amd64], cross-compilation [linux_amd64]
I 2016/12/15 08:17:32 main.go:188: Wide is running [172.17.0.71:17070]
D 2016/12/15 08:18:35 playgrounds.go:97: User [playground] has [0] sessions
D 2016/12/15 08:18:37 playgrounds.go:97: User [playground] has [0] sessions
E 2016/12/15 08:18:39 run.go:84: fork/exec /root/playground/8b7cc38b4c12e6fde5c4d15a4f2f32e5: permission denied

**Comment by 88250** [comment]
add docker volume: `-v ~/wide/playground:/playground/`
then setup arg: `-docker=true -playground=/playground`

**Comment by xladykiller** [comment]
@88250 
it don't work, 
E 2016/12/19 03:42:32 run.go:84: fork/exec /root/playground/8b7cc38b4c12e6fde5c4d15a4f2f32e5: permission denied

**Comment by 88250** [comment]
Do you add `-docker=true -playground=/playground` in setup arg?

**Comment by xladykiller** [comment]
in Dockfile, i add params in CMD
WORKDIR /root

CMD ["/root/bin","-docker=true","-channel=ws://192.168.7.7:17070", "-playground=/root/playground/"]

**Comment by 88250** [comment]
I don't think I can help you.. 

Please research it by yourself, sorry :(
