### ISSUE TITLE
没有足够的隔离环境和限制

### ISSUE THREAD

**Issue by horsley** [b3log/wide#296]
编写一段代码执行命令kill，能把站点服务kill掉……

建议 chroot或者docker隔离

**Comment by horsley** [comment]
此外，数据没有隔离，playground和workspace目录，可以读到别人workspace的内容

**Comment by 88250** [comment]
多谢指出，后期考虑看下怎么改进。

**Comment by 88250** [comment]
### 解决方案

1. 通过 Docker 容器执行用户代码编译好的程序，限制资源使用
2. 通过 `timeout` 限制执行时长

v1.6.0 中进行改进。
