### ISSUE TITLE
arm交叉编译，放到树莓派3上报错

### ISSUE THREAD

**Issue by seaweedman** [b3log/wide#297]
报错内容：
before malloc heap initialized
fatal error:panic on m stack:
before malloc heap initialized
anic:
before malloc heap initialized
available

怎么回事呢

**Comment by 88250** [comment]
没有遇到过这个问题，请自救 :)

**Comment by seaweedman** [comment]
wide.b3log.org上生成的arm可执行文件确实有点问题。我在树莓派上搭建环境(go1.74)，编译就能正常输出(我只是打印了一下'hello world',没有CGO什么的)

**Comment by 88250** [comment]
@seaweedman 收到，在线服务的 go 版本有点老，可能是这个原因造成的，等有空我升级。多谢反馈 :)
