### ISSUE TITLE
反复存档会发生runtime.throw 

### ISSUE THREAD

**Issue by khjde1207** [b3log/wide#300]
反复存档会发生 
goroutine 67 [running]:
runtime.throw(0x8646ac, 0x15)
        /golang/go/src/runtime/panic.go:566 +0x95 fp=0xc4200479e8 sp=0xc4200479c8
runtime.mapassign1(0x7e9400, 0xc420122ba0, 0xc420047b58, 0xc420047b68)
        /golang/go/src/runtime/hashmap.go:458 +0x8ef fp=0xc420047ad0 sp=0xc4200479e8
github.com/b3log/wide/i18n.load(0xc4208fa170, 0x5)
        /golang/gowork/src/github.com/b3log/wide/i18n/locales.go:74 +0x255 fp=0xc420047bc8 sp=0xc420047ad0
github.com/b3log/wide/i18n.Load()
        /golang/gowork/src/github.com/b3log/wide/i18n/locales.go:53 +0x12b fp=0xc420047c48 sp=0xc420047bc8
main.i18nLoad.func1(0xa33040, 0xc4200901a0, 0xc420466000)
        /golang/gowork/src/github.com/b3log/wide/main.go:416 +0x2b fp=0xc420047c78 sp=0xc420047c48
net/http.HandlerFunc.ServeHTTP(0xc420255fb0, 0xa33040, 0xc4200901a0, 0xc420466000)
。。。
。。
。
以上错误。 
i18n/locales.go 
43横
func Load() 
每次存档，呼出Load()函数。 
Locales map 容量挺大的。 
这个有意义么？

**Comment by 88250** [comment]
谢谢你的 PR https://github.com/b3log/wide/pull/301
