### ISSUE TITLE
update go runtime to latest stable version

### ISSUE THREAD

**Issue by bruceauyeung** [b3log/wide#302]
currently the online wide service is using Go 1.4.2 , which is completely obsolete and will never get any critical security fixes.

> Each major Go release obsoletes and ends support for the previous one. For example, if Go 1.5 has been released, then it is the current release and Go 1.4 and earlier are no longer supported. We fix critical problems in the current release as needed by issuing minor revisions (for example, Go 1.5.1, Go 1.5.2, and so on).
As a special case, we issue minor revisions for critical security problems in both the current release and the previous release. For example, if Go 1.5 is the current release then we will issue minor revisions to fix critical security problems in both Go 1.4 and Go 1.5 as they arise.

quoted from https://golang.org/doc/devel/release.html#policy

so please update the go runtime to latest stable version , thanks !

**Comment by bruceauyeung** [comment]
i strongly recommend upgrading go to latest stable version, otherwise user can not leverage Vendor mechanism and binary-only package

**Comment by 88250** [comment]
Thank you, I will upgrade it asap.

**Comment by bruceauyeung** [comment]
after golang upgraded, i suggest `go get` in wide to clone codes to `vendor` directory, its a better practise.

**Comment by 88250** [comment]
Thank you, I will try it.
