### ISSUE TITLE
go get does not work properly

### ISSUE THREAD

**Issue by bruceauyeung** [b3log/wide#306]
i have a go file `string_test.go`, and in this test file, i import some third party packages like this:
```
import (
	. "github.com/smartystreets/goconvey/convey"
	"testing"
) 
```

when i open this file and click `go get` menu in run menu,  output panel says:

> START [go get]
> [go get] SUCCESS

but when i click `Test` ,there is an error:
> START [go test]
> [go test] ERROR
> \# goplayground
> defer2_test.go:4:2: cannot find package "github.com/smartystreets/goconvey/convey" in any of:
> /usr/local/go/src/github.com/smartystreets/goconvey/convey (from $GOROOT)
> /workspaces/bruceauyeung/src/github.com/smartystreets/goconvey/convey (from $GOPATH)
> FAIL	goplayground [setup failed]

**Comment by 88250** [comment]
v1.6.0 将默认使用 Go Modules，并通过 go mod + goproxy 解决依赖下载问题。

**Comment by 88250** [comment]
已经完整迁移到 go mod 上，在设置命令执行环境变量中写死了：

* GO111MODULE=on
* GOPROXY=https://goproxy.cn

代码在 output/outputs.go 中的 setCmdEnv 函数。
