### ISSUE TITLE
go build with args 

### ISSUE THREAD

**Issue by khjde1207** [b3log/wide#308]
output/cross.go 78 横  
cmd = exec.Command("go", "build", "-ldflags", "-H windowsgui")
这样的话，在windows系统上可以隐藏console窗口。 
可不可以加入 go build 设置功能？

**Comment by 88250** [comment]
你建议 UI 在哪里进行配置这个呢？

**Comment by khjde1207** [comment]
在偏好设定里面, 或menubar里加入编译配置菜单。 
跟liteIDE相似。

**Comment by khjde1207** [comment]
![img2](https://cloud.githubusercontent.com/assets/18232924/23639949/c4ced8b6-032d-11e7-8f87-a6977c29452b.png)
比如像图片一样。

**Comment by 88250** [comment]
配置后该用户的所有项目都会使用同一个配置吗？

**Comment by khjde1207** [comment]
LITEIDE是，个个文件使用个个配置。 
![4](https://cloud.githubusercontent.com/assets/18232924/23640429/01196e28-0331-11e7-8e7a-03f9ade72c8b.png)
但我觉得以用户设置比较好。 
每次修改太麻烦。

**Comment by 88250** [comment]
好的，我参考一下 :)

**Comment by khjde1207** [comment]
谢谢

**Comment by 88250** [comment]
1. 加入 go build 参数
2. 交叉编译设置 https://github.com/golang/go/wiki/WindowsCrossCompiling
