### ISSUE TITLE
Enhance cross-compilation

### ISSUE THREAD

**Issue by khjde1207** [b3log/wide#322]
go 1.5 以后的版本是不是不用构造交叉编译环境啊？

我这次下了1.8版本以后，不用构造交叉编译环境，直接可以交叉编译。 
用一下命令： 
env GOOS=windows GOARCH=amd64 go build
env GOOS=linux GOARCH=amd64 go build

所以我在GOROOT/pkg/tool里新建目录 windows_386，  windows_ard64 在目录里又新建 6个目录。（1,2,3,4,5,6）
这样就可以交叉编译呢。 

是不是得修改，检查交叉编译环境的功能呢？ 
https://github.com/b3log/wide/blob/master/util/go.go
GetCrossPlatforms()

![1](https://cloud.githubusercontent.com/assets/18232924/26090094/91504460-3a3d-11e7-93da-297632c6c3f2.png)

**Comment by 88250** [comment]
收到，确实应该需要更新一下了，谢谢反馈。

**Comment by khjde1207** [comment]
谢谢
