### ISSUE TITLE
打不开goapi文件，无法参考api

### ISSUE THREAD

**Issue by windyslove** [b3log/wide#323]
如题，打不开file面板下的goapi文件，无法参考api
问下有自动补全吗

fmt.Println("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx")也没有输出在output面板

**Comment by 88250** [comment]
配置 $GOROOT 环境变量后试试？

**Comment by windyslove** [comment]
我是在win10运行的，安装go的时候就自动有goroot了

**Comment by 88250** [comment]
看下日志有没有警告啥的

**Comment by windyslove** [comment]
能看到日志了，但是buid&run之后怎么停止

**Comment by 88250** [comment]
先到 https://wide.b3log.org/ 试用一下？

**Comment by windyslove** [comment]
已经试用了。本地的可以使用停止按钮停止了，就是api无法打开了

**Comment by 88250** [comment]
麻烦看下 `go env` 的结果

**Comment by windyslove** [comment]
PS C:\Users\windys\Downloads\wide-1.5.2-windows-amd64\conf> go env
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=E:\DemoWorkspace\gowork
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\windys\AppData\Local\Temp\go-build254444635=/tmp/go-build -gno-record-gcc-switches
set CXX=g++
set CGO_ENABLED=1
set PKG_CONFIG=pkg-config
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
PS C:\Users\windys\Downloads\wide-1.5.2-windows-amd64\conf>

**Comment by 88250** [comment]
咦，看上去都是对的。我本地和你的差不多，API 目录我这里本地是好的。

**Comment by windyslove** [comment]
运行前需要什么别的配置吗，我是下载下后改了个ip

wide.json
{
    "IPold": "${ip}",
    "IP": "127.0.0.1",
    "Port": "8989",
    "Context": "",
    "Server": "{IP}:{Port}",
    "StaticServer": "",
    "LogLevel": "debug",
    "Channel": "ws://{IP}:{Port}",
    "HTTPSessionMaxAge": 86400,
    "StaticResourceVersion": "${time}",
    "MaxProcs": 4,
    "RuntimeMode": "dev",
    "WD": "${pwd}",
    "Locale": "en_US",
    "Playground": "${home}/playground",
    "UsersWorkspaces": "${WD}/workspaces",
    "AllowRegister": true,
    "Autocomplete": true
}

**Comment by 88250** [comment]
这个配置也应该是对的。

**Comment by 88250** [comment]
对了，如果你拉了源码的话可以运行一下测试用例，看看是否都 ok，谢谢。

**Comment by khjde1207** [comment]
你用IP进的？

**Comment by 88250** [comment]
我先关闭这个 issue 了，如果还有问题就更贴吧。
