### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by IamQiuTian** [b3log/wide#327]
编译完成后配置了conf/users/admin.json中的用户名和密码，然后启动程序，但输入用户名和密码登录后显示Login Error， 求老铁们指点。

**Comment by 88250** [comment]
你看下密码加密那段代码，我记得好像是 MD5+Salt

**Comment by IamQiuTian** [comment]
老铁，默认密码是什么， 或者怎么创建一个新用户？

**Comment by 88250** [comment]
默认密码是 admin/admin，新用户的话直接注册。

**Comment by IamQiuTian** [comment]
好的， 谢谢。
