### ISSUE TITLE
已有执行中的任务。build失败使已经运行中的程序不能停止。

### ISSUE THREAD

**Issue by khjde1207** [b3log/wide#330]
我不知道该怎么说。有点难。 我已经解决了。
步骤： 
1.
package main
...
.. 
http.ListenAndServe(":5000", server) 
做一个简单的服务器。按f6运行。 
2.在Source code上故意出错。 
http.ListenAndServe(":5000", server---)
3. CTRL +S 储存。 
上面 □ 按键 变成 ▶, 
4. 用ps -ef  看， 刚运行中的程序还在执行。 但在wide上不能关闭。

**Comment by 88250** [comment]
谢谢 PR 先 :)
