### ISSUE TITLE
自带的web例子，在浏览器无法访问

### ISSUE THREAD

**Issue by kekemuyu** [b3log/wide#332]

**Comment by 88250** [comment]
你是本地的 Wide 还是？

**Comment by kekemuyu** [comment]
本地和在线都不行

**Comment by kekemuyu** [comment]
`fmt.Println("Open http://wide.b3log.org:" + port + " in your browser to see the result")`
点击run后，上边的代码不打印

**Comment by 88250** [comment]
这是输出实现的问题，以后有时间会修复，谢谢 :)

**Comment by kekemuyu** [comment]
刚又试了下，把端口改成固定的后，虽然不打印，但可以访问了，确实是输出问题
