### ISSUE TITLE
running dockerized wide but could not build project

### ISSUE THREAD

**Issue by Lt0** [b3log/wide#333]
Here is the output from server: 
root@lt:~# docker run --rm -p 7070:7070 88250/wide:latest ./wide -docker=true -channel=ws://0.0.0.0:7070
D 2018/01/15 01:53:46 wide.go:183: Conf: 
{
    "IP": "${ip}",
    "Port": "7070",
    "Context": "",
    "Server": "{IP}:{Port}",
    "StaticServer": "",
    "LogLevel": "debug",
    "Channel": "ws://{IP}:{Port}",
    "HTTPSessionMaxAge": 86400,
    "StaticResourceVersion": "${time}",
    "MaxProcs": 4,
    "RuntimeMode": "dev",
    "WD": "${pwd}",
    "Locale": "en_US",
    "Playground": "${home}/playground",
    "UsersWorkspaces": "${WD}/workspaces",
    "AllowRegister": true,
    "Autocomplete": true
}
D 2018/01/15 01:53:46 wide.go:187: ${pwd} [/wide/gogogo/src/github.com/b3log/wide]
D 2018/01/15 01:53:46 wide.go:197: ${user.home} [/root]
D 2018/01/15 01:53:46 wide.go:232: ${ip} [172.17.0.3]
D 2018/01/15 01:53:46 wide.go:263: ${time} [1515981226983219319]
D 2018/01/15 01:53:47 main.go:90: host [go1.8.3, linux_amd64], cross-compilation [darwin_amd64 linux_amd64 windows_amd64 linux_arm darwin_386 linux_386 windows_386]
I 2018/01/15 01:53:47 main.go:188: Wide is running [172.17.0.3:7070]
W 2018/01/15 01:53:53 main.go:226: Not found user [lightime]
I 2018/01/15 01:54:04 users.go:415: Created a user [lightime]
D 2018/01/15 01:54:04 main.go:242: User [lightime] has [0] sessions
E 2018/01/15 01:54:05 main.go:300: Session [4218248319332910433] not found
D 2018/01/15 01:55:14 users.go:229: Created a HTTP session [5738240618958890740] for user [lightime]
D 2018/01/15 01:55:14 main.go:242: User [lightime] has [0] sessions
E 2018/01/15 01:55:15 main.go:300: Session [3699611088471512293] not found
D 2018/01/15 01:56:57 main.go:242: User [lightime] has [0] sessions
E 2018/01/15 01:56:57 main.go:300: Session [6508609883438288000] not found
D 2018/01/15 01:58:28 users.go:229: Created a HTTP session [8919374857598549717] for user [lightime]
D 2018/01/15 01:58:28 main.go:242: User [lightime] has [0] sessions
E 2018/01/15 01:58:29 main.go:300: Session [5664746092043902147] not found

Here is the notification from client(web):
ERROR | Disconnected from server, trying to reconnect it [sid=6508609883438288000]
-- | --

**Comment by 88250** [comment]
Try to specify `IP` config item.

**Comment by Lt0** [comment]
It seems that I have to specify the host IP as 127.0.0.1 to make it work(visit it by running firefox on the same server). This limitation means that I could not visit the service from other client. In general, we don't run browser on server directly.

**Comment by Lt0** [comment]
Maybe the root cause of this issue is that the IPs of host and container should be the same to make it work.

**Comment by 88250** [comment]
I thin you need specify IP using public network interface. I close this issue, thank you feedback,
