### ISSUE TITLE
ip错误导致运行失败

### ISSUE THREAD

**Issue by kekemuyu** [b3log/wide#335]
![default](https://user-images.githubusercontent.com/8471788/39090834-876667d2-461b-11e8-920e-4ffaf653ee71.png)

**Comment by 88250** [comment]
手动设置一下 conf/wide.json 里面的 IP，`${ip}` 是自动获取，有的时候会有问题，你本地用的话改成 `127.0.0.1` 就好了。

**Comment by kekemuyu** [comment]
改好后服务可以运行了,但项目不能编译.错误提示如下: 



kekemuyu@126.com
 
发件人： D
发送时间： 2018-04-22 11:12
收件人： b3log/wide
抄送： kekemuyu; Author
主题： Re: [b3log/wide] ip错误导致运行失败 (#335)
手动设置一下 conf/wide.json 里面的 IP，${ip} 是自动获取，有的时候会有问题，你本地用的话改成 127.0.0.1 就好了。

**Comment by 88250** [comment]
没有报错日志嘛。

**Comment by kekemuyu** [comment]
User [kekemuyu] has [0] sessions
Session [2780955311249438191] not found
Session没找到这个是错误吧,日志前有"E"

**Comment by 88250** [comment]
你用什么浏览器？打开 F12 看下网络里面有没有连接不通的。

**Comment by kekemuyu** [comment]
终于好了,可能是ip改的地方不对
开始时是改的main函数中的:err := http.ListenAndServe(":7070", nil)
后来改的wide.c中的Wide.IP = "127.0.0.1"
可能是其他地方也在用Wide.IP,所以不能偷懒只改main中ip

**Comment by kekemuyu** [comment]
有时间学习一下wide的源码,写得非常棒,而且我觉的云ide是未来的方向.我现在用wide的原因是,我想用chromebook做开发,喜欢它的轻便,这样我在阿里部署wide,打开chrome就可以开发了,真实天造地设的一对(:p

**Comment by 88250** [comment]
加油 😀
