### ISSUE TITLE
wide verison 1.5.3 for go 1.10 can't build or run   

### ISSUE THREAD

**Issue by IamQiuTian** [b3log/wide#337]
点击运行后一直是红色方框状态， 没有其他信息输出。

**Comment by IamQiuTian** [comment]
所以。。日志在哪。。找不到

**Comment by IamQiuTian** [comment]
F12:  WebSocket connection to 'ws://10.163.19.41/notification/ws?sid=1074838263646283898' failed: WebSocket is closed before the connection is established

**Comment by 88250** [comment]
websocket 建立失败了，你服务端有用了 nginx 反代的话也要配置下 ws 反代。

**Comment by IamQiuTian** [comment]
没有使用NGINX反代， 直接启动的服务。

**Comment by 88250** [comment]
看下服务端日志，控制台输出有没有报错。

**Comment by IamQiuTian** [comment]
I 2018/05/16 09:54:32 main.go:188: Wide is running [10.163.19.41:80]
D 2018/05/16 10:01:26 users.go:229: Created a HTTP session [5577006791947779410] for user [qiutian]
D 2018/05/16 10:01:26 main.go:242: User [qiutian] has [0] sessions
E 2018/05/16 10:01:48 main.go:300: Session [6023378043881239018] not found
D 2018/05/16 10:02:53 main.go:242: User [qiutian] has [0] sessions
E 2018/05/16 10:02:53 main.go:300: Session [5271585091488117232] not found
D 2018/05/16 10:09:10 test.go:117: User [qiutian, 5271585091488117232] is running [go test] [runningId=3555252951866568970]
D 2018/05/16 10:09:10 test.go:133: User [qiutian, 5271585091488117232] 's running [go test] [runningId=3555252951866568970] has done
D 2018/05/16 10:09:12 install.go:68: go install /code/golang/src/wide/workspaces/qiutian/src/hello
D 2018/05/16 10:09:12 install.go:122: User [qiutian, 5271585091488117232] is running [go install] [id=6488834397503326732, dir=/code/golang/src/wide/workspaces/qiutian/src/hello]
D 2018/05/16 10:09:17 main.go:242: User [qiutian] has [0] sessions
E 2018/05/16 10:09:17 main.go:300: Session [8439175782489389567] not found
D 2018/05/16 10:14:28 main.go:242: User [qiutian] has [0] sessions
E 2018/05/16 10:14:29 main.go:300: Session [2120184874979646198] not found
D 2018/05/16 10:18:00 vet.go:117: User [qiutian, 2120184874979646198] is running [go vet] [runningId=3560711614588397926]
D 2018/05/16 10:18:00 vet.go:133: User [qiutian, 2120184874979646198] 's running [go vet] [runningId=3560711614588397926] has done
D 2018/05/16 13:46:47 main.go:242: User [qiutian] has [0] sessions
E 2018/05/16 13:46:47 main.go:300: Session [2406611357931593325] not found
D 2018/05/16 13:47:13 main.go:242: User [qiutian] has [0] sessions
E 2018/05/16 13:47:13 main.go:300: Session [1074838263646283898] not found

**Comment by IamQiuTian** [comment]
是因为我新注册的用户权限不够吗？

**Comment by 88250** [comment]
看上去还是 ws 建立有问题，你跟下代码看看吧。

**Comment by IamQiuTian** [comment]
emmm...
