### ISSUE TITLE
Choose branch in Git Clone

### ISSUE THREAD

**Issue by villadalmine** [b3log/wide#344]
I want to know if can added the next configuration.
I need to add the branch in the moment I clone the repo. Actually every time that you clone something will clone master, I need go inside de docker and change the branch manually.

961767366036463235] has done: Cloning into 'fxx.git -b yaml'...
fatal: unable to access 'https://user:passowrd:gitlab.xxx.com/xx/xx.git -b yaml/': Illegal port number

**Comment by 88250** [comment]
We will remove git support in https://github.com/b3log/wide/issues/356
