### ISSUE TITLE
目录访问权限优化

### ISSUE THREAD

**Issue by guhan121** [b3log/wide#350]
### 你在什么场景下需要该功能？
我现在有这样一个场景，我自己提供一下基础的api和类似于sdk一样的公共函数，然后使用者有多个，想把他们独立出来，但又能访问写的函数。  如果按照现在的思路，我应该是建多个账户，每个账户都复制一份。这样会带来不统一的问题。

### 描述可能的解决方案

能不能像系统api那样可以在网页里面显示公共api, 但是其他用户不能在里面添加，删除修改。只能由我去修改。

**Comment by 88250** [comment]
二次开发一下，参考系统 api 那部分的处理。

**Comment by guhan121** [comment]
谢谢！
