### ISSUE TITLE
Vulnerability: read and write to any file

### ISSUE THREAD

**Issue by 0x2E** [b3log/wide#355]
### 描述问题

Sensitive system files can be read through code or soft links.

### 重现步骤

**Method 1**：by code

1. Writing code in the editor to read any file, such as /etc/passwd
2. Click the green button at the top to compile and run about three times (I don't know why three)
3. /etc/passwd will be read out

**Method 2**：by git or compressed file

1. Create a soft link to a sensitive file, such as /etc/passwd, on a Linux
```bash
ln -s /etc/passwd ./passwdLink
```
2. compress the soft link
```bash
zip -y test.zip passwdLink
```
3. upload zip and unzip it. when you open a link file, the local file that you point to is opened
4. change and save the file if the user running wide has permission

### 期待的结果

Sensitive system files should not be read.

### 截屏或录像

![1](https://i.imgur.com/RJsDXj8.png)

![1](https://i.imgur.com/LdNUy7S.png)

**Comment by 88250** [comment]
Thank you, we will fix it, duplicated with https://github.com/b3log/wide/issues/296

**Comment by 88250** [comment]
wide.b3log.org 已经部署最新代码，如果方便请帮忙检查一下是否还有问题，谢谢！

**Comment by 0x2E** [comment]
@88250 你好，上文提到的 **Method 2** 仍然可用，编辑器在打开文件时并没有**判断是否为符号链接**。说 duplicated 有点冤枉我了 😂 

![hash](https://i.imgur.com/bbB9kCQ.png)

**Comment by 88250** [comment]
不好意思，我重新打开这个问题了。

上传这个问题感觉比较严重，后续我将该功能完整去掉吧，感谢反馈。

**Comment by 0x2E** [comment]
除了上传压缩包，导入 Git 仓库也可以引入链接文件，建议导入 Git 的地方也控制一下。

**Comment by 88250** [comment]
收到，git 功能也打算移除了，谢谢指教。

**Comment by 88250** [comment]
* 上传、git 功能都已经移除（UI 稍后移除）
* 运行用户程序通过 docker 进行隔离并加入了执行超时控制
* 之前的符号链接文件已经删除了

如果有空还请再帮忙看看是否还有其他漏洞，万分感谢 ❤️

**Comment by 0x2E** [comment]
好的，以后如果发现新问题的话我会及时反馈 😄
