### ISSUE TITLE
go get x包失败

### ISSUE THREAD

**Issue by idoly** [b3log/wide#359]
**请先看[《提问的智慧》](https://hacpai.com/article/1536377163156)**，并尝试到[讨论区](https://hacpai.com/tag/wide)搜寻资料解决问题。

----

### 描述问题

go get x包出现错误

开始 [go build [-i]]
../github.com/mattn/go-isatty/isatty_tcgets.go:7:8: cannot find package "golang.org/x/sys/unix" in any of:
/usr/lib/go-1.12/src/golang.org/x/sys/unix (from $GOROOT)
/home/wide/data/workspaces/17639669/src/golang.org/x/sys/unix (from $GOPATH)
[go build] 失败

请尽量清晰精准地描述你碰到的问题。

### 重现步骤
代码如下，点击go get运行
```
package main

import "github.com/gin-gonic/gin"
import "net/http"

func main() {

	router := gin.Default()

	v1 := router.Group("/v1")
	{
		v1.GET("/login", output1)
		v1.GET("/submit", output1)
		v1.GET("/post", output1)
	}

	v2 := router.Group("/v2")
	{
		v2.POST("/login", output2)
		v2.POST("/submit", output2)
		v2.POST("/post", output2)
	}

	router.Run(":8080")
}

func output1(c *gin.Context) {
	name := c.Param("name")
	c.String(http.StatusOK, "hello,%s  [get]", name)
}

func output2(c *gin.Context) {
	name := c.DefaultPostForm("name", "Xyz")
	c.String(http.StatusOK, "hello,%s  [post]", name)
}
```
请描述如何重现这个问题：

2. Click on '...'
3. Scroll down to '...'

### 期待的结果

请尽量清晰精准地描述你所期待的结果。

### 截屏或录像

如果可能，请尽量附加截图或录像来描述你遇到的问题。

### 桌面端环境

- OS: [e.g. windows, mac, linux]

### 移动端环境

- Device: [e.g. iPhone8]
- OS: [e.g. iOS12]

### 其他信息

请提供其他附加信息帮助我们诊断问题。

**Comment by 88250** [comment]
你好，这个问题我们稍后会通过 go mod + goproxy 解决，具体请移步到 https://github.com/b3log/wide/issues/306 上，感谢反馈！
