### ISSUE TITLE
求助，无法build

### ISSUE THREAD

**Issue by kisskillkiss** [b3log/wide#364]
**请先看[《提问的智慧》](https://hacpai.com/article/1536377163156)**，并尝试到[讨论区](https://hacpai.com/tag/wide)搜寻资料解决问题。

----

### 描述问题
$ export GOPROXY=https://goproxy.io
$ export GO111MODULE=on
$ go build
go: downloading golang.org/x/net v0.0.0-20190514140710-3ec191127204
go: downloading golang.org/x/text v0.3.2
go: downloading golang.org/x/sys v0.0.0-20190515190549-87c872767d25
go: extracting golang.org/x/sys v0.0.0-20190515190549-87c872767d25
build github.com/b3log/wide: cannot load golang.org/x/net/publicsuffix: unexpected EOF

请尽量清晰精准地描述你碰到的问题。

### 重现步骤

请描述如何重现这个问题：

2. Click on '...'
3. Scroll down to '...'

### 期待的结果

请尽量清晰精准地描述你所期待的结果。

### 截屏或录像

如果可能，请尽量附加截图或录像来描述你遇到的问题。

### 桌面端环境
mac 10.14.5 (18F132)
- OS: [e.g. windows, mac, linux]

### 移动端环境

- Device: [e.g. iPhone8]
- OS: [e.g. iOS12]

### 其他信息

请提供其他附加信息帮助我们诊断问题。

**Comment by 88250** [comment]
换个代理试试：

```
export GOPROXY=https://goproxy.cn
```

**Comment by kisskillkiss** [comment]
Great! 非常感谢！可以了！
