### ISSUE TITLE
Cant install - GO build is failing - As per my understanding Dependency issue

### ISSUE THREAD

**Issue by surapuramakhil** [b3log/wide#368]
**请先看[《提问的智慧》](https://hacpai.com/article/1536377163156)**，并尝试到[黑客派](https://hacpai.com)搜寻资料解决问题。

----

### 描述问题

Cant install - GO build is failing

### 重现步骤

请描述如何重现这个问题：

akhil-kfn@tech-akhil-laptop-ubuntu: \~/OpenSource/wide$ go get github.com/visualfc/gotools github.com/nsf/gocode
akhil-kfn@tech-akhil-laptop-ubuntu:~/OpenSource/wide$ go build
main.go:32:2: cannot find package "github.com/b3log/gulu" in any of:
	/usr/lib/go-1.10/src/github.com/b3log/gulu (from $GOROOT)
	/home/akhil-kfn/go/src/github.com/b3log/gulu (from $GOPATH)
main.go:33:2: cannot find package "github.com/b3log/wide/conf" in any of:
	/usr/lib/go-1.10/src/github.com/b3log/wide/conf (from $GOROOT)
	/home/akhil-kfn/go/src/github.com/b3log/wide/conf (from $GOPATH)
main.go:34:2: cannot find package "github.com/b3log/wide/editor" in any of:
	/usr/lib/go-1.10/src/github.com/b3log/wide/editor (from $GOROOT)
	/home/akhil-kfn/go/src/github.com/b3log/wide/editor (from $GOPATH)
main.go:35:2: cannot find package "github.com/b3log/wide/event" in any of:
	/usr/lib/go-1.10/src/github.com/b3log/wide/event (from $GOROOT)
	/home/akhil-kfn/go/src/github.com/b3log/wide/event (from $GOPATH)
main.go:36:2: cannot find package "github.com/b3log/wide/file" in any of:
	/usr/lib/go-1.10/src/github.com/b3log/wide/file (from $GOROOT)
	/home/akhil-kfn/go/src/github.com/b3log/wide/file (from $GOPATH)
main.go:37:2: cannot find package "github.com/b3log/wide/i18n" in any of:
	/usr/lib/go-1.10/src/github.com/b3log/wide/i18n (from $GOROOT)
	/home/akhil-kfn/go/src/github.com/b3log/wide/i18n (from $GOPATH)
main.go:38:2: cannot find package "github.com/b3log/wide/notification" in any of:
	/usr/lib/go-1.10/src/github.com/b3log/wide/notification (from $GOROOT)
	/home/akhil-kfn/go/src/github.com/b3log/wide/notification (from $GOPATH)
main.go:39:2: cannot find package "github.com/b3log/wide/output" in any of:
	/usr/lib/go-1.10/src/github.com/b3log/wide/output (from $GOROOT)
	/home/akhil-kfn/go/src/github.com/b3log/wide/output (from $GOPATH)
main.go:40:2: cannot find package "github.com/b3log/wide/playground" in any of:
	/usr/lib/go-1.10/src/github.com/b3log/wide/playground (from $GOROOT)
	/home/akhil-kfn/go/src/github.com/b3log/wide/playground (from $GOPATH)
main.go:41:2: cannot find package "github.com/b3log/wide/session" in any of:
	/usr/lib/go-1.10/src/github.com/b3log/wide/session (from $GOROOT)
	/home/akhil-kfn/go/src/github.com/b3log/wide/session (from $GOPATH)
### 期待的结果

请尽量清晰精准地描述你所期待的结果。

### 截屏或录像

如果可能，请尽量附加截图或录像来描述你遇到的问题。

### 桌面端环境

- OS: [e.g. windows, mac, linux] ubuntu 18.04

### 移动端环境

- Device: [e.g. iPhone8]
- OS: [e.g. iOS12]

### 其他信息

请提供其他附加信息帮助我们诊断问题。

**Comment by 88250** [comment]
需要启用 go modules。
