### ISSUE TITLE
Debugger

### ISSUE THREAD

**Issue by 88250** [b3log/wide#8]
- 断点
- 逐语句、逐过程
- 变量
- 调用堆栈

实现支撑：
- gdb
- https://code.google.com/p/ogle
- https://github.com/derekparker/delve

**Comment by crackgame** [comment]
调试啥时候能用哦，亲

**Comment by 88250** [comment]
@crackgame 等 Go 1.5 发布后可能可以实现。

**Comment by crackgame** [comment]
密切关注，亲，加油啊！

**Comment by 88250** [comment]
暂不考虑支持了。
