### ISSUE TITLE
Editor with vim-mode support

### ISSUE THREAD

**Issue by Xuyuanp** [b3log/wide#83]

**Comment by edwardxie** [comment]
vim模式Codemirror是支持的，也可以在源码自己改下，或者等作者加入快捷方式，
可以参考，http://codemirror.net/demo/vim.html

**Comment by 88250** [comment]
We'll implement it in recent days.

**Comment by 88250** [comment]
![image](https://cloud.githubusercontent.com/assets/873584/7560309/81490bd4-f7f4-11e4-9484-049fe2570ef4.png)

请大家帮忙测试 :grapes:
